### ISSUE TITLE
Nested Navigators

### ISSUE THREAD

**Issue by paomosca** [pxue/react-native-navigation-mobx-demo#1]
Tnx for contributing with this example to integrate mobx to manage react-navigation.

I'm trying to apply the same approach for a more complex (but very common) case:

I've a modal stack containing some modal screens and a nested stack with screen mode:

this is the root nav:

```
const Root = StackNavigator({
  MainNav: {
    screen: MainNav,
  },
  LoginScreen: {
    screen: LoginScreen,
  }
}, {
  mode: 'modal',
  headerMode: 'none'
});
```

this is the nested one:

```
const MainNav = StackNavigator({
  HomeScreen: {
    screen: HomeScreen
  },
  AnotherScreen: {
    screen: AnotherScreen
  }
}, {
  headerMode: 'none'
});
```

Now to initialize navigationState in navigationStore if i set:

```
@observable.ref navigationState = {
    index: 0,
    routes: [
      { key: "home", routeName: "HomeScreen" },
    ],
  }
```

if get this error: 

```
There is no route defined for key HomeScreen. Must be one of: 'MainNav','LoginScreen'
```

if is set: 

```
@observable.ref navigationState = {
    index: 0,
    routes: [
      { key: "main", routeName: "MainNav" },
    ],
  }
```

if get this error: 

```
Expect nav state to have routes and index, {"key":"main","routeName":"MainNav"}
```

any hint?

**Comment by tauren** [comment]
@paomosca Did you come up with a solution that you can share?

**Comment by joskar** [comment]
@paomosca 
try to initialize your navigationState with 
```

@observable.ref navigationState = {
		index: 0,
		routes: [
			{ key: "MainNav", routeName: "MainNav", index: 0, routes: [
				{ key: "HomeScreen", routeName: "HomeScreen" },
				{ key: "AnotherScreen", routeName: "AnotherScreen" }
			]},
			{ key: "LoginScreen", routeName: "LoginScreen" }
		]
	}
```

**Comment by pxue** [comment]
@paomosca have you tried @JosKar's solution?

This is what I do in my own application, I have the same "Login" -> "Main" setup.

by default my navigationState is initialized as this:
```
  @observable.ref navigationState = {
    index: 0,
    routes: [
      { key: "Login", routeName: "Login" },
    ],
  }
```

and in my `LoginScreen`, I have `if logged in redirect to main app screen` logic. ie:

```
  componentDidMount() {
    const { api, navigation: { dispatch } } = this.props;
    const success = await api.login(type, payload);
    if (success) {
      dispatch(resetAction("MainNav"));
    }
  }
```

Not sure if it solves your problem, but this has been working for me.

**Comment by pxue** [comment]
I've added a login / redirect example in this commit https://github.com/pxue/react-native-navigation-mobx-demo/commit/a803c7426a3ec7be28082680174e0311072b8f52
