### ISSUE TITLE
ReferenceError: Can't find variable: store

### ISSUE THREAD

**Issue by mnlbox** [pxue/react-native-navigation-mobx-demo#2]
Hi @pxue ,
I try implement React Navigation with Mobx based on your tutorial but it's return below error:
```
ReferenceError: Can't find variable: store
```
I think it's related to this line:
https://github.com/pxue/react-native-navigation-mobx-demo/blob/master/App.js#L85

Are you have any suggestion to fix it?

**Comment by pxue** [comment]
hey @mnlbox I've added a v2 branch, which should include fix for the store issue.
